
image: maven:3.9-eclipse-temurin-17

stages:
  - test

cache:
  paths:
    - ~/.m2/repository

test_api:
  stage: test
  script:
    - mvn -B -DskipTests=false test
  artifacts:
    when: always
    paths:
      - target/surefire-reports
      - reports/allure-results
